# Site settings
title: Daniel Nikolovski | Web / UX / SEO
email: hello@danielnikolovski.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Web designer from Sweden, with a burning passion for UX & SEO.
// url: "http://danielnikolovski.com"
url: "http://danielnikolovski.com"
twitter_username: danneniko
github_username:  danneniko
highlighter: pygments
encoding: utf-8
permalink: /:title
post_dirs: false

# Build settings
markdown: kramdown
