# Site settings
title: Daniel Nikolovski | Web / UX / SEO
email: hello@danielnikolovski.com
description: > # this means to ignore newlines until "baseurl:"
  Jag är en front end designer från Eslöv, med en brinnande passion för UX & SEO.
url: "http://danielnikolovski.com"
twitter_username: danneniko
github_username:  danneniko
highlighter: pygments
encoding: utf-8
permalink: /:title
post_dirs: false

# Build settings
markdown: kramdown
