# Site settings
title: Daniel Nikolovski | Webb / UX / SEO
email: hello@danielnikolovski.com
description: > # this means to ignore newlines until "baseurl:"
  Jag är en webbdesigner från Eslöv, med en brinnande passion för UX & SEO.
url: "http://danielnikolovski.com"
twitter_username: danneniko
github_username:  danneniko
highlighter: pygments
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
