
function getParameterByName(name){name=name.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");var regexS="[\\?&]"+name+"=([^&#]*)";var regex=new RegExp(regexS);var results=regex.exec(window.location.search);if(results==null)
return"";else
return decodeURIComponent(results[1].replace(/\+/g," "));}
function isTouchDevice(){return(typeof(window.ontouchstart)!='undefined')?true:false;}
function writeEmailAddress(a,x,y){b='@';c='.';var output='';output+=a;output+=b;output+=x;output+=c;output+=y;document.write('<a href=\"mailto:'+output+'\" title=\"'+output+'\">'+output+'</a>');}
function writeEmailAddressNoLink(a,x,y){b='@';c='.';var output='';output+=a;output+=b;output+=x;output+=c;output+=y;document.write(output);}
;;;
window.viewportWidth=0;$(window).resize(function(){window.viewportWidth=$(window).width();chairPosition(true);});$(function(){window.viewportWidth=$(window).width();chairPosition(false);$('#Social img').mouseenter(function(){var src=$(this).attr('src');src=src.replace('.png','Over.png');$(this).attr('src',src);}).mouseleave(function(){var src=$(this).attr('src');src=src.replace('Over.png','.png');$(this).attr('src',src);});$('#Translate img').mouseenter(function(){var src=$(this).attr('src');src=src.replace('.png','Over.png');$(this).attr('src',src);}).mouseleave(function(){var src=$(this).attr('src');src=src.replace('Over.png','.png');$(this).attr('src',src);});});function chairPosition(resize){if(window.viewportWidth>1640){if(resize){$('#Chair').fadeIn(500);}else{$('#Chair').show();}}else{$('#Chair').hide();}}
$.getDocHeight=function(){return Math.max($(document).height(),$(window).height(),document.documentElement.clientHeight);};$(function(){$('.wall .item:has(a)').mouseenter(function(){var position=$(this).position();var image=$(this).find('img');var defaults={left:position.left,top:position.top,width:$(image).width(),height:$(image).height(),zIndex:$(this).css("z-index")};var newWidth=defaults.width+10;var newHeight=defaults.height+parseInt(10*defaults.height/defaults.width);var newLeft=defaults.left-5;var newTop=defaults.top-parseInt((newHeight-defaults.height)/2);if($(image).is("[data-hover-src]")){$(image).attr("data-src",$(image).attr("src"));$(image).attr("src",$(image).attr("data-hover-src"));}
$(this).data("defaults",defaults);$(this).css('z-index','200');$(image).animate({'width':newWidth+'px','height':newHeight+'px'},100);$(this).animate({'left':newLeft+'px','top':newTop+'px'},100);}).mouseleave(function(){var defaults=$(this).data("defaults");var image=$(this).find('img');if($(image).is("[data-src]")){$(image).attr("src",$(image).attr("data-src"));}
$(this).css('z-index',defaults.zIndex);$(image).animate({'width':defaults.width+'px','height':defaults.height+'px'},100);$(this).animate({'left':defaults.left+'px','top':defaults.top+'px'},100);});});$(function(){$(".swappable-byline:has(.byline)").hover(function(){var byline=$(this).find(".byline");var defaults={content:byline.text()};byline.data("defaults",defaults);byline.text(byline.data("hover-content"))},function(){var byline=$(this).find(".byline");var defaults=byline.data("defaults");byline.text(defaults.content)});});$(function(){$(".validation-summary-errors").dialog({modal:true,title:"Fel!",buttons:{Ok:function(){$(this).dialog("close");}}});});
;;;
window.currentDashboardId=null;window.currentDashboardZindex=null;window.currentDashboardLeft=null;window.currentDashboardTop=null;window.currentDashboardWidth=null;window.currentDashboardHeight=null;function loadDashboard(){var left=0;var delay=0
$(document).ready(function(){if($.cookie('loadedDashboard')!='true'){loadDashboard();$.cookie('loadedDashboard','true');}else{window.loadDashboardDone=true;$('#Dashboard .Item').show();$('#Dashboard .Intro').show();}
$('#Dashboard .Item').mouseenter(function(){if(window.loadDashboardDone){var position=$(this).position();var left=position.left;var top=position.top;var image=$(this).find('img');var width=$(image).width();var height=$(image).height();window.currentDashboardId=$(this).attr('id');window.currentDashboardZindex=$(this).css('z-index');window.currentDashboardLeft=left;window.currentDashboardTop=top;window.currentDashboardWidth=width;window.currentDashboardHeight=height;var newWidth=width+10;var newHeight=height+parseInt(10*height/width);var newLeft=left-5;var newTop=top-parseInt((newHeight-height)/2);if($(image).is("[data-hover-src]")){$(image).attr("data-src",$(image).attr("src"));$(image).attr("src",$(image).attr("data-hover-src"));}
$(this).css('z-index','200');$(image).animate({'width':newWidth+'px','height':newHeight+'px'},100);$(this).animate({'left':newLeft+'px','top':newTop+'px'},100);}}).mouseleave(function(){if(window.loadDashboardDone){var image=$(this).find('img');if($(image).is("[data-src]")){$(image).attr("src",$(image).attr("data-src"));}
$(this).css('z-index',window.currentDashboardZindex);$(image).animate({'width':window.currentDashboardWidth+'px','height':window.currentDashboardHeight+'px'},100);$(this).animate({'left':window.currentDashboardLeft+'px','top':window.currentDashboardTop+'px'},100);}});});
;;;
